# src/agent/nodes/generate_answer_cloud.py
# Cloud answer path — used only when all sources are PUBLIC.
# Currently passes through since existing retrieval nodes already
# generate the answer. This node tags the path as cloud.
# Future: replace with cloud_chat_model call for public-only queries.

from src.types.langgraph_state_types import OverallState


def generate_answer_cloud(state: OverallState) -> OverallState:
    """
    Cloud answer path.
    Answer already generated by retrieval nodes.
    Tags the state with cloud dispatch path.
    Future: regenerate answer using cloud_chat_model for public queries.
    """
    print("[generate_answer_cloud] answer ready — dispatched via cloud path")
    return {
        **state,
        "dispatch_decision": "cloud",
    }
