# src/agent/nodes/generate_answer_onpremise.py
# Passes the answer through from the retrieval node.
# The actual answer was already generated inside exact_query
# or semantic_retrieval using the on-premise model.
# This node exists to complete the dispatch branch cleanly.

from src.types.langgraph_state_types import OverallState


def generate_answer_onpremise(state: OverallState) -> OverallState:
    """
    On-premise answer path.
    Answer already generated by exact_query or semantic_retrieval
    using qwen3.6:27b on DGX Spark.
    Just tags the state with the dispatch path.
    """
    print("[generate_answer_onpremise] answer ready from on-premise model")
    return {
        **state,
        "dispatch_decision": "private",
    }
